### ISSUE TITLE
CSS-specificity problems with `className` proxing

### ISSUE THREAD

**Issue by SuperOl3g** [alfa-laboratory/cn-decorator#6]
Setting external `className` for blocks **isn't  a safe way** to overwrite CSS styles.
If we use only BEM-named classes it will have equal priority so that if there are same CSS properties browser will choose the last one found in the final CSS file.

AFAIK (but it is not exactly) [bem-core](https://github.com/bem/bem-core) bundler generate dependency graph so files with custom styles always go after default styles.

React developers usually use [webpack](https://github.com/webpack/webpack) with [style-loader](https://github.com/webpack-contrib/style-loader) and [css-loader](https://github.com/webpack-contrib/css-loader) for bundling with styles. In common case **it doesn't guarantee correct order of compiled styles**.

So the question is how did you fix this problem?
Maybe some special postCSS plugin for increasing specificity or something else?)

**Comment by GREENpoint** [comment]
Setting external `className` is a last mile. We recommend for teams to avoid this feature. And use it only in extreme issues. But we have not issue with last `style-loader` and `css-loader` in case of incorrect order.
